name: Build and Test IRC Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build library
      run: make libtool.a
    
    - name: Build server
      run: make server
    
    - name: Build bot
      run: make bot
    
    # TODO
    # - name: Run tests
    #   run: make tests
